name: py15
channels:
  - pytorch
  - salilab
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - biopython=1.78
  - biotite=0.33.0
  - blas=1.0=mkl
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - decorator=5.1.1
  - dssp=3.0.0
  - executing=0.8.3
  - expat=2.4.9
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipython=8.3.0
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libboost=1.67.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.8.4
  - numexpr=2.8.3
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.2
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - pytz=2022.1
  - qt=5.9.7
  - readline=8.1.2
  - requests=2.28.1
  - scikit-learn=1.0.1
  - scipy=1.7.3
  - setuptools=63.4.1
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.2
  - stack_data=0.2.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.2
  - traitlets=5.1.1
  - typing_extensions=4.3.0
  - tzdata=2022c
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.11
  - zstd=1.4.9
